### ISSUE TITLE
Missing GUI

### ISSUE THREAD

**Issue by WynXC** [CowNowK/CS2-External-Cheat#1]
I run the .exe but the GUI doesn't appear even pressing INS key.

**Comment by CowNowK** [comment]
> I run the .exe but the GUI doesn't appear even pressing INS key.

@WynXC   Can you send a screenshot? A cmd will open after running successfully and the GUI will appear. If error occured you can see some info in the cmd

**Comment by WynXC** [comment]
@CowNowK The CMD opened up and stated running successfully, just that the GUI didn't appear.

**Comment by WynXC** [comment]
![Untitled1](https://github.com/CowNowK/CS2-External-Cheat/assets/95940184/cf630905-b9d8-4bf3-8951-8935cdb4b91a)

**Comment by CowNowK** [comment]
![image](https://github.com/CowNowK/CS2-External-Cheat/assets/133740174/5560a211-b2cf-4c1b-a9c0-8e69ffbae444)
I haven't encountered such an error before, so I'm not sure if it's related to the game settings. Could you check if mine is the same as yours?

**Comment by WynXC** [comment]
@CowNowK Yes, thanks. It's related to the settings.
